### ISSUE TITLE
Build fails in production due to missing create-compilers modules

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#193]
```
2017-06-21T08:52:40.423282+00:00 app[web.1]: Error: Cannot find module '../dist/create-compilers'
2017-06-21T08:52:40.423282+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-06-21T08:52:40.423283+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-06-21T08:52:40.423284+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-06-21T08:52:40.423284+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-06-21T08:52:40.423285+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/tapestry-wp/bin/tapestry-build:3:25)
2017-06-21T08:52:40.423286+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-06-21T08:52:40.423286+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-06-21T08:52:40.423287+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-06-21T08:52:40.423288+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-06-21T08:52:40.423288+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
```

`postinstall` not firing, maybe move that step to prepublish.

**Comment by thomasdigby** [comment]
Fixed in `2.0.0-11`
