### ISSUE TITLE
Purging homepage cache results in server error

### ISSUE THREAD

**Issue by ecoad** [shortlist-digital/tapestry-wp#241]
#### Expected behaviour
```js
{
  status: "Purged /"
}
```

#### Actual behaviour
```js
{
  message: "An internal server error occurred",
  statusCode: 500,
  error: "Internal Server Error"
}
```

#### Steps to reproduce
When visiting `http://www.example.com/purge//`

#### Environment
2.0.0-16

**Comment by thomasdigby** [comment]
```
2017-07-24T17:09:57.290066+00:00 app[web.1]:     Error: Uncaught error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
2017-07-24T17:09:57.290068+00:00 app[web.1]:     at invariant (/app/node_modules/invariant/invariant.js:35:15)
2017-07-24T17:09:57.290068+00:00 app[web.1]:     at match (/app/node_modules/react-router/lib/match.js:44:165)
2017-07-24T17:09:57.290069+00:00 app[web.1]:     at handler (/app/.tapestry/webpack:/node_modules/tapestry-wp/src/server/handle-purge.js:20:7)
2017-07-24T17:09:57.290070+00:00 app[web.1]:     at Object.internals.handler (/app/node_modules/hapi/lib/handler.js:101:51)
2017-07-24T17:09:57.290071+00:00 app[web.1]:     at request._protect.run (/app/node_modules/hapi/lib/handler.js:32:23)
2017-07-24T17:09:57.290071+00:00 app[web.1]:     at internals.Protect.run (/app/node_modules/hapi/lib/protect.js:59:12)
2017-07-24T17:09:57.290072+00:00 app[web.1]:     at exports.execute (/app/node_modules/hapi/lib/handler.js:26:22)
2017-07-24T17:09:57.290073+00:00 app[web.1]:     at each (/app/node_modules/hapi/lib/request.js:404:16)
2017-07-24T17:09:57.290074+00:00 app[web.1]:     at iterate (/app/node_modules/items/lib/index.js:36:13)
2017-07-24T17:09:57.290074+00:00 app[web.1]:     at done (/app/node_modules/items/lib/index.js:28:25)
2017-07-24T17:09:57.069152+00:00 heroku[router]: at=info method=GET path="/purge//" host=mr-hyde-production.herokuapp.com request_id=c3a82b40-3bd7-4da9-a3f9-0a1152412b8a fwd="31.221.59.187,52.56.127.51" dyno=web.1 connect=0ms service=80ms status=500 bytes=517 protocol=http
```

**Comment by jonsherrard** [comment]
(scrubbed some production data from trace)

**Comment by thomasdigby** [comment]
🤦‍♂️
