### ISSUE TITLE
Tests fail in lint-staged pre commit command

### ISSUE THREAD

**Issue by jonsherrard** [shortlist-digital/tapestry-wp#94]
`npm test` is working, but I'm getting an error from a library inside `node_modules` when they run via `lint-staged` pre-commit hooks:

```
🚫  npm test found some errors. Please fix them and try committing again.

[Deprecation] In glamor v3 this file will be published as a standalone package: "glamor-server". See https://github.com/threepointone/glamor/issues/204 for more information.
[Deprecation] In glamor v3 this file will be published as a standalone package: "glamor-reset". See https://github.com/threepointone/glamor/issues/204 for more information.
/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/location-origin/dist/location-origin.js:5
  loc = window.location;
        ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/location-origin/dist/location-origin.js:5:9)
    at Object.<anonymous> (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/location-origin/dist/location-origin.js:22:4)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/src/client/webpack.entry.js:5:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/jonsherrard/projects/tapestry-working/tapestry-wp/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I've forced the code upto: `feature/remove-window-scroll-to` branch

**Comment by mathewhawley** [comment]
@thomasdigby – didn't you have a similar issue not too long ago? I'll have a google around

**Comment by mathewhawley** [comment]
@jonsherrard – can't see that branch? Have you pushed it up?

**Comment by mathewhawley** [comment]
In the meantime, maybe has something to do with this? http://stackoverflow.com/questions/34059644/mocha-command-giving-referenceerror-window-is-not-defined

**Comment by thomasdigby** [comment]
As it's only testing the server functionality it shouldn't be touching any DOM related JS, and _I think_ the error goes away if you remove the `location-origin` polyfill.

**Comment by jonsherrard** [comment]
Yeah it felt like the under context of `npm run` running => `lint-staged` => running => `npm test`, some of the .ignore files weren't being followed correctly.

However, `rm -rf node_modules && npm install` did fix this.
